# Generated by Django 3.1.1 on 2020-09-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voyage',
            old_name='passager',
            new_name='passager_fk',
        ),
    ]
