# Generated by Django 3.1.1 on 2020-09-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20200904_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conducteur',
            name='image_vehicule',
        ),
        migrations.AddField(
            model_name='conducteur',
            name='image_car',
            field=models.ImageField(blank=True, upload_to='images_car'),
        ),
    ]
